### ISSUE TITLE
API - check user's early withdrawal value of pT token

### ISSUE THREAD

**Issue by cxtmh** [superhedge-finance/api#3]
Input:
User's wallet address
SHProduct address
No of blocks to withdraw

Output:
Real-time market value of pT token (USDC)

Only returns value when:
+ user's wallet balance SHProduct's SHToken >= min withdrawal block size AND
+ SHProduct status = 3

**Comment by phongcpt72** [comment]
https://github.com/superhedge-finance/legacy-api/pull/1

I already deployed into dev-erc20-arbitrum

**Comment by cxtmh** [comment]
pushed to https://github.com/superhedge-finance/api/tree/dev
